"""Updated relationships

Revision ID: 0a22bd370635
Revises: 45188fc7b09f
Create Date: 2025-06-04 19:06:41.562393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a22bd370635'
down_revision: Union[str, None] = '45188fc7b09f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cvs', sa.Column('uploaded_at', sa.String(), server_default=sa.text('now()'), nullable=True))
    op.add_column('listings', sa.Column('company_id', sa.Integer(), nullable=False))
    op.add_column('listings', sa.Column('link', sa.String(), nullable=True))
    op.create_foreign_key(None, 'listings', 'companies', ['company_id'], ['id'])
    op.drop_column('listings', 'company')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('company', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'listings', type_='foreignkey')
    op.drop_column('listings', 'link')
    op.drop_column('listings', 'company_id')
    op.drop_column('cvs', 'uploaded_at')
    # ### end Alembic commands ###
