"""Add stored queries table

Revision ID: 6b635902536e
Revises: e529316486e9
Create Date: 2025-06-22 14:01:15.598123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b635902536e'
down_revision: Union[str, None] = 'e529316486e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stored_queries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keywords', sa.Text(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('radius', sa.String(), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stored_queries')
    # ### end Alembic commands ###
