"""Fix'

Revision ID: b053d95bb282
Revises: a708f2572971
Create Date: 2025-06-21 19:50:44.041256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b053d95bb282'
down_revision: Union[str, None] = 'a708f2572971'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listings', 'link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'listings', ['link'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'listings', type_='unique')
    op.alter_column('listings', 'link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
