"""Added multiple improvements

Revision ID: fbabaf50856b
Revises: 0bb98dc31143
Create Date: 2025-06-21 15:24:10.640444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbabaf50856b'
down_revision: Union[str, None] = '0bb98dc31143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('keywords', sa.String(), nullable=True),
    sa.Column('embedding', sa.String(), nullable=True),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cvs')
    op.add_column('listings', sa.Column('keywords', sa.String(), nullable=True))
    op.add_column('listings', sa.Column('embedding', sa.String(), nullable=True))
    op.add_column('listings', sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'scraped_at')
    op.drop_column('listings', 'embedding')
    op.drop_column('listings', 'keywords')
    op.create_table('cvs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', sa.VARCHAR(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('cvs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cvs_pkey'))
    )
    op.drop_table('resumes')
    # ### end Alembic commands ###
